CREATE TABLE STUDENT_INFO(sid int unique,stud_name varchar(20) not null,stude_score decimal(5,2) default 20);
ALTER TABLE STUDENT_INFO DROP INDEX sid;
ALTER TABLE STUDENT_INFO ADD PRIMARY KEY (sid);
INSERT INTO  STUDENT_INFO VALUES
 (1,'Manu',100.8),
 (2,'Kumar',153),
 (3,'Hima',148),
 (4,'Malu',155);
SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENT_INFO SET stude_score = stude_score +5 WHERE  stude_score > 150 ; 
SELECT * FROM STUDENT_INFO;

CREATE TABLE WORKER (
WORKER_ID int(5),
FIRST_NAME VARCHAR(15),
LAST_NAME VARCHAR(15),
SALARY FLOAT(8),
JOINING_DATE DATE,
DEPARTMENT VARCHAR(15),
PRIMARY KEY (WORKER_ID)
);
INSERT INTO WORKER VALUE
(1, 'Monika','Arora',100000,'2014-02-20','HR'),(2,'Niharika','Verma',80000 ,'2014-06-11','Admin'),
(3 ,'Vishal', 'Singhal', 300000,'2014-02-20','HR'), (4,'Amitabh','Singh',500000,'2014-02-20' ,'Admin'), 
(5,'Vivek','Bhati',500000,'2014-06-11','Admin'),(6,'Vipul','Diwan',200000 ,'2014-06-11','Account'),
(7,'Satish','Kumar',75000,'2014-01-20','Account'), (8,'Geetika','Chauhan', 90000,' 2014-04-11', ' Admin');
SELECT * FROM WORKER;

CREATE TABLE BONUS(WORKER_ID INT,BONUS_DATE DATE,BONUS_AMOUNT INT,
CONSTRAINT FK FOREIGN KEY(WORKER_ID) REFERENCES WORKER(WORKER_ID) ON UPDATE CASCADE ON DELETE CASCADE);
INSERT INTO BONUS VALUE
(1,' 2016-02-20', 5000),
(2, '2016-06-11' ,3000),
(3, '2016-02-20', 4000),
(1, '2016-02-20', 4500),
(2 ,'2016-06-11', 3500);

SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

SELECT * FROM WORKER ORDER BY (FIRST_NAME);

SELECT * FROM WORKER WHERE FIRST_NAME NOT IN('Vipul','Satish');

SELECT * FROM WORKER WHERE DEPARTMENT ='Admin';

SELECT * FROM WORKER WHERE SALARY BETWEEN 100000 AND 500000; 

SELECT UPPER(FIRST_NAME) AS FIRST_NAME FROM WORKER;

SELECT DISTINCT DEPARTMENT FROM WORKER;

SELECT SUBSTRING(FIRST_NAME ,1,3) AS FIRST_NAME FROM WORKER;

SELECT RTRIM(FIRST_NAME) AS FIRST_NAME FROM WORKER;

SELECT LTRIM(DEPARTMENT) AS DEPARTMENT FROM WORKER;

SELECT DISTINCT DEPARTMENT,length(DEPARTMENT) AS LENGTH_OF_WORD FROM WORKER;

SELECT REPLACE(FIRST_NAME,'a','A') AS FIRST_NAME FROM WORKER;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT,SALARY,BONUS_AMOUNT FROM WORKER,BONUS 
WHERE WORKER.WORKER_ID = BONUS.WORKER_ID AND BONUS_AMOUNT > 4000;

DELETE FROM WORKER WHERE WORKER_ID = 7;
SELECT * FROM WORKER;
SELECT * FROM BONUS; 

ALTER TABLE BONUS DROP CONSTRAINT FK;
ALTER TABLE BONUS ADD CONSTRAINT FK_NEW FOREIGN KEY(WORKER_ID) REFERENCES WORKER(WORKER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

DELETE FROM WORKER WHERE WORKER_ID = 8;
SELECT * FROM WORKER;